# Generated by Django 5.1.5 on 2025-02-13 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_category_description_en_category_description_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='category',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='category',
            name='description_uz',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_uz',
        ),
    ]
